export default {
  START_ADD_TODO: 'START_ADD_TODO',
  CHANGE_INPUT: 'CHANGE_INPUT',
  TOGGLE_TODO: 'TOGGLE_TODO',
  START_GET_TODO: 'START_GET_TODO',
  GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
  GET_TODO_FAILED: 'GET_TODO_FAILED'
}
